# Generated by Django 6.0.4 on 2026-08-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartitem_order_orderitem_userprofile_wishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ambassador_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/ambassadors/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/hero/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brands/logos/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
