# Generated by Django 6.0.4 on 2026-08-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_ambassador_image_brand_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ambassador_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='ambassador_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
