# Generated by Django 6.0.4 on 2026-08-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_brand_ambassador_description_brand_ambassador_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='ambassador_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='brands/ambassadors/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='ambassador_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='brands/ambassadors/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='ambassador_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='brands/ambassadors/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='ambassador_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='brands/ambassadors/'),
        ),
    ]
